name: Lint
run-name: Lint
on: [push]
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🔎 Let's lint the code"
      - name: Golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0